---
stages:
  - test
  - analyze
  - build
  - deploy

include:
  template: SAST.gitlab-ci.yml

variables:
  # To make sure that latest git tag gets fetched
  # or version() function will fail
  GIT_DEPTH: "100"

###########################
# Templates               #
#                         #
# make sure all jobs use  #
# architecture tags.      #
###########################
.job:
  before_script:
    - ./.gitlab-ci/$CI_JOB_STAGE/$CI_JOB_NAME.sh setup
  needs: []
  except: [schedules]
  script:
    - ./.gitlab-ci/$CI_JOB_STAGE/$CI_JOB_NAME.sh

.dind:
  extends: .job
  image: docker:24
  variables:
    DOCKER_DRIVER: overlay2
    DOCKER_BUILDKIT: 1
  services:
    - docker:24-dind

#######
# Tests
#######
.dispatcher:
  extends: .job
  stage: test
  image: registry.gitlab.com/lava/ci-images/$CI_JOB_NAME
  artifacts:
    reports:
      junit: dispatcher.xml

.server:
  extends: .job
  stage: test
  image: registry.gitlab.com/lava/ci-images/$CI_JOB_NAME
  artifacts:
    reports:
      junit: server.xml

amd64/dispatcher-debian-11: {"extends": ".dispatcher"}
amd64/server-debian-11: {"extends": ".server"}
amd64/dispatcher-debian-12: {"extends": ".dispatcher"}
amd64/server-debian-12: {"extends": ".server"}
amd64/dispatcher-debian-13: {"extends": ".dispatcher"}
amd64/server-debian-13: {"extends": ".server"}
aarch64/dispatcher-debian-11:
  extends: .dispatcher
  tags:
    - saas-linux-medium-arm64
  only:
    refs:
      - master
aarch64/server-debian-11:
  extends: .server
  tags:
    - saas-linux-medium-arm64
  only:
    refs:
      - master

###########
# Analyze #
###########
.analyze:
  extends: .job
  image: registry.gitlab.com/lava/ci-images/amd64/analyze
  stage: analyze
  except:
    refs:
      - tags

black:
  extends: .analyze

code_quality:
  extends: .analyze
  artifacts:
    reports:
      codequality: gl-code-quality-report.json

coverage:
  extends: .analyze
  image: registry.gitlab.com/lava/ci-images/amd64/server-debian-12
  coverage: '/(?i)total.*? (100(?:\.0+)?\%|[1-9]?\d(?:\.\d+)?\%)$/'
  artifacts:
    paths:
      - htmlcov/
      - coverage.xml
    reports:
      coverage_report:
        coverage_format: cobertura
        path: coverage.xml

dockerfiles:
  extends: .analyze

schemas:
  extends: .analyze

pylint:
  extends: .analyze
  image: registry.gitlab.com/lava/ci-images/amd64/analyze-debian-13

sast:
  stage: analyze
  variables:
    SAST_DEFAULT_ANALYZERS: "bandit"


codespell:
  extends: .analyze
  image: registry.gitlab.com/lava/ci-images/amd64/analyze-debian-13

django_migrations:
  extends: .analyze
  image: registry.gitlab.com/lava/ci-images/amd64/server-debian-11

mypy:
  extends: .analyze
  image: registry.gitlab.com/lava/ci-images/amd64/analyze-debian-13

#########
# Build #
#########
doc:
  extends: .job
  stage: build
  image: registry.gitlab.com/lava/ci-images/amd64/pkg-debian-11
  artifacts:
    paths:
      - doc/v2/_build/html

.debian_build:
  extends: .job
  stage: build
  except: []
  image: registry.gitlab.com/lava/ci-images/amd64/pkg-debian-12
  artifacts:
    paths:
      - _build/*.deb
      # handle native package - need to publish the source
      - _build/*.tar.xz
      - _build/*.dsc
      - _build/*.changes
      - _build/*.buildinfo

debian/11:
  extends: .debian_build
  image: registry.gitlab.com/lava/ci-images/amd64/pkg-debian-11

debian/12:
  extends: .debian_build
  image: registry.gitlab.com/lava/ci-images/amd64/pkg-debian-12

debian/13:
  extends: .debian_build
  image: registry.gitlab.com/lava/ci-images/amd64/pkg-debian-13

.docker:
  extends: .dind
  stage: build
  before_script:
    - .gitlab-ci/$CI_JOB_STAGE/docker.sh setup
  script:
    - SERVICE="$(echo "$CI_JOB_NAME" | cut -d "-" -f 3)"
    - git fetch --prune --tags --unshallow
    - .gitlab-ci/$CI_JOB_STAGE/docker.sh "$SERVICE"

.docker_aarch64:
  extends: .docker
  only:
    refs:
      - master
      - tags
  tags:
    - saas-linux-medium-arm64
  services:
    - name: docker:24-dind
      # Workaround for arm64 network connectivity issues
      # https://gitlab.com/gitlab-org/gitlab/-/issues/473739#workaround
      command: ["--mtu=1400"]

docker-amd64-dispatcher: {"extends": ".docker"}
docker-amd64-server: {"extends": ".docker"}
docker-aarch64-dispatcher: {"extends": ".docker_aarch64"}
docker-aarch64-server: {"extends": ".docker_aarch64"}

##########
# Deploy #
##########
.publish-packages:
  stage: deploy
  needs:
    - debian/11
    - debian/12
  trigger:
    project: lava/lava-apt-repo
  variables:
    PARENT_PROJECT_NAME: $CI_PROJECT_NAME
    PARENT_PROJECT_REF: $CI_COMMIT_REF_NAME

publish-packages/daily:
  extends: .publish-packages
  rules:
    - if: '$CI_PIPELINE_SOURCE == "schedule" && $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH'
  variables:
    LAVA_APT_CHANNEL: daily

publish-packages/release:
  extends: .publish-packages
  only:
    refs:
      - tags
  variables:
    LAVA_APT_CHANNEL: release

pages:
  stage: deploy
  only:
    refs:
      - tags
  needs:
    - doc
  script:
    - cp -a doc/v2/_build/html public
  artifacts:
    paths:
      - public

publish-docs:
  stage: deploy
  only:
    refs:
      - tags
  needs:
    - pages
  trigger:
    project: lava/lava-docs
  variables:
    PARENT_PROJECT_NAME: $CI_PROJECT_NAME
    PARENT_PROJECT_REF: $CI_COMMIT_REF_NAME
